# Generated by Django 3.1.5 on 2021-01-17 17:01

from django.db import migrations, models
import utils.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='defaults/user.png', upload_to=utils.file_utils.profile_photo_directory_path),
        ),
    ]
