# Generated by Django 5.0.6 on 2024-05-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_about_profile_dob_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_number",
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
