# Generated by Django 5.0.6 on 2024-05-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
