# Generated by Django 5.0.6 on 2024-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="specialization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
