# Generated by Django 3.1.5 on 2021-03-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timerange',
            unique_together={('start', 'end')},
        ),
    ]
