# Generated by Django 3.1.5 on 2021-03-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_education_experience_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='from_year',
            new_name='year_of_completion',
        ),
        migrations.RemoveField(
            model_name='education',
            name='to_year',
        ),
    ]
