# Generated by Django 5.0.6 on 2024-05-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "doctors",
            "0005_experience_designation_alter_experience_working_here",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Specialization",
        ),
    ]
